/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_imtld_ilog_DisplayLine */

#ifndef _Included_fr_imtld_ilog_DisplayLine
#define _Included_fr_imtld_ilog_DisplayLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_imtld_ilog_DisplayLine
 * Method:    displayLine
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_fr_imtld_ilog_DisplayLine_displayLine
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
